### ISSUE TITLE
You use AES-256-CTR, file size limit?

### ISSUE THREAD

**Issue by snap9** [Tarsnap/scrypt#100]
https://github.com/Tarsnap/scrypt/blob/master/FORMAT

With CTR mode and 128-bit block size, the file size limit is about 64 GB for the same IV.

Was the decision to use CTR done deliberately, because you reckoned that most people will encrypt less than 64 GB?

Just wondering, and should the scrypt command line tool warn before encrypting larger files than 64 GB?

**Comment by cperciva** [comment]
What makes you think that CTR mode is limited to 64 GB?  You can encrypt up to 2^68 bytes.

**Comment by snap9** [comment]
@cperciva It depends on how much of the 128 bit block size you use for the IV and how much for the counter. I was using an example IV of 96 bits and counter 32 bits (total 96+32=128) that I saw in my textbook. Sorry about that. My bad.

Looks like 64 bits + 64 bits is the standard CTR way and that's what you're using.

**Comment by snap9** [comment]
@cperciva I do have one question though, where does the IV for CTR come from? I don't see that in the FORMAT document.

**Comment by snap9** [comment]
@cperciva I do have one question though. You use a fixed nonce = 0. Is that safe because of the fixed of the randomized salt? Do you think a randomized 64-bit nonce (in addition to the salt) would be worth it, for more security?

**Comment by cperciva** [comment]
Right, if you only have a 32-bit counter then you'd be limited to 64 GB.

The fixed nonce of 0 is safe because you'll never see two messages encrypted with the same AES key -- yes, because of the random salt which is mixed with the passphrase to derive the AES key.  It's probably clearer if you read "nonce" in the definition of CTR mode as "message ID".
