### ISSUE TITLE
Misleading documentation on the scrypt website regarding libscrypt-kdf

### ISSUE THREAD

**Issue by sternenseemann** [Tarsnap/scrypt#277]
Seems like the paragraph about "Using scrypt as a KDF" on the [website](https://www.tarsnap.com/scrypt.html) was written before `libscrypt-kdf`: It suggests the header is `crypto_scrypt.h` and the function `crypto_scrypt()`. I believe this should be `scrypt-kdf.h` and `scrypt_kdf()` respectively?

**Comment by gperciva** [comment]
Thanks, @sternenseemann!

Definitely agreed that `scrypt_kdf()` should be mentioned on the website (and README).  I'm checking with @cperciva about whether we want to keep the current discussion about `crypto_scrypt()` or not.  If this was a new project, we'd only mention the `scrypt_kdf()` function, but there's ten years of people using `crypto_scrypt()` because that's all we had in the past.

**Comment by sternenseemann** [comment]
The function name is not that big of an issue in my opinion since they both can be used since `scrypt_kdf` is just an alias for `crypto_scrypt`. My main concern is that the documentation to me seemed to suggest that the header was `crypto/scrypt.h` or `crypto_scrypt.h` while `make install` would only install `scrypt-kdf.h` and likewise the debian package also only installs that header.

**Comment by gperciva** [comment]
Good point, thanks!  I've rewritten it to discuss `libscrypt-kdf` first.

One tiny nitpick: `make install` will only install `scrypt-kdf.h` if you use `./configure --enable-libscrypt-kdf`; it doesn't happen by default.  Granted, it looks like many packagers are enabling this (which is great!), so maybe we don't need to worry so much about people installing it from scratch.

**Comment by gperciva** [comment]
The README and website have been updated, thanks!
