### ISSUE TITLE
scryptenc_buf/scryptdec_buf in app

### ISSUE THREAD

**Issue by joagre** [Tarsnap/scrypt#92]
Hi,
I am thinking about using scryptenc_buf/scryptdec_buf to store my app's
private keys on the device. There are "KeyStore" mechanisms available on
both on Android[1] and iOS[2] etc but they are different beasts with the
need for device specific solutions for each.

It would be ideal to use NaCl[3] for the pk crypto and then use
scryptenc_buf/scryptdec_buf to store the private key on the device.

The same solution could then be used on all type of devices with all the
benefits which comes with NaCl and scrypt.

The native "KeyStore" mechanisms in iOS and Android comes with their own
pros of course.

Is this a lame idea? Anyone?

Cheers
/Joakim

[1] https://developer.android.com/training/articles/keystore.html
[2] https://developer.apple.com/library/content/documentation/Security/Conceptual/keychainServConcepts/iPhoneTasks/iPhoneTasks.html
[3] https://nacl.cr.yp.to/box.html

**Comment by cperciva** [comment]
This might be better directed to the scrypt mailing list (https://www.tarsnap.com/lists.html) since there are some people on that list who have used scrypt in other ways.  But in general I'd say that yes, scrypt is a good tool for protecting private data on a device, assuming you can get your users to enter (and remember) a passphrase.  Whether this is the best implementation for that purpose, I don't know; I understand that Android uses scrypt internally, so they might have a better-tuned implementation.

**Comment by joagre** [comment]
Thanks for the input. I will take the question to the scrypt mailing list as well.

Kind regards
/Joakim
